name: Test and Lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Replace with your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint # Replace with your linting script from package.json

      - name: Run Jest tests
        run: npm test # Replace with your test script from package.json
